app/Http/routes.php
<?php
use App\Http\Controllers\PesananController;

Route::auth();
Route::get('/', 'HomeController@index');
Route::get('/blog/{seo}', 'HomeController@artikel');
Route::get('/blog', 'HomeController@blog');
Route::get('/blog/kategori/{id}', 'HomeController@blogKategori');
Route::get('/cara-belanja', 'HomeController@caraBelanja');
Route::get('/kontak', 'HomeController@kontak');
Route::get('/yunus', 'HomeController@blog');
Route::get('/about', 'HomeController@about');
Route::get('/retur', 'HomeController@retur');
Route::get('/wellcome', 'HomeController@wellcome');
Route::resource('konfirmasi', 'KonfirmasiController');
Route::resource('confirm', 'ReturController');
Route::get('/biaya-ongkir', 'HomeController@biayaongkir');

Route::group(['middleware'=>'auth', 'prefix'=>'admin'], function(){
    Route::resource('statis', 'StatisController');
    Route::resource('produk', 'ProdukController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('slideshow', 'SlideshowController');
    Route::resource('user', 'UserController');
    Route::resource('kategoriartikel', 'KategoriArtikelController');
    Route::resource('artikel', 'ArtikelController');
    Route::resource('ongkir', 'OngkirController');
    Route::get('pesanan', 'PesananController@index');
    Route::get('pesanan/detail/{kode}', 'PesananController@detailOrder');
    Route::post('ubahstatus', 'PesananController@ubahStatus');
    Route::get('laporan', 'LaporanController@index');
    Route::post('hapuspesanan', 'PesananController@hapusPesanan');

});

//CART
Route::get('/gallery-produk', 'TokoController@galleryProduk');
Route::get('/detail-produk/{seo}', 'TokoController@detailproduk');
Route::get('/kategori-produk/{kategori_id}/{seo}', 'TokoController@kategoriproduk');
Route::get('product/cart/{id}', 'TokoController@cart');
Route::get('cart-content', 'TokoController@cartContent');
Route::post('cart-update', 'TokoController@updateCart');
Route::get('cart/delete/{rowid}', 'TokoController@deleteCart');
Route::get('cart/checkout', 'TokoController@checkout');
Route::get('cart/destroy', 'TokoController@destroy');


//USER AREA PELANGGAN
Route::group(['middleware'=>'auth', 'prefix'=>'user'], function(){
  Route::get('cart/account', 'OrderController@account');
  Route::get('cart/edit', 'OrderController@editaccount');
  Route::get('cart/orders', 'OrderController@order');
  Route::get('cart/histori/{master_kode}', 'OrderController@historiorder');
  Route::post('cart/savepelanggan', 'OrderController@savePelanggan');
  Route::get('cart/saveorder', 'OrderController@saveOrder');
  Route::get('cart/ordersukses', 'OrderController@orderSukses');
});


//VIEW
View::composer('frontend', function($view){
  $view->kategoriproduk = App\Kategori::all();
  $view->kategoriartikel = App\KategoriArtikel::all();

});

resources/views/admin_template.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $page_title or "AdminLTE Dashboard" }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ asset("/bower_components/admin-lte/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/bower_components/admin-lte/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ asset("/bower_components/admin-lte/dist/css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue">
<div class="wrapper">

    <!-- Header -->
    @include('header')

    <!-- Sidebar -->
    @include('sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $page_title or "Page Title" }}
                <small>{{ $page_description or null }}</small>
            </h1>
            <!-- You can dynamically generate breadcrumbs here -->
            <ol class="breadcrumb">
                <li><a href="{{ url('/statis') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">{{ isset($page_title) ? $page_title : 'Halaman Admin' }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Footer -->
    @include('footer')

</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.1.3 -->
<script src="{{ asset ("/bower_components/admin-lte/plugins/jQuery/jQuery-2.2.0.min.js") }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ asset ("/bower_components/admin-lte/bootstrap/js/bootstrap.min.js") }}" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="{{ asset ("/bower_components/admin-lte/dist/js/app.min.js") }}" type="text/javascript"></script>
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('/bower_components/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1');
    //bootstrap WYSIHTML5 - text editor
    $(".textarea").wysihtml5();
  });
</script>

</body>
</html>

resources/views/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Butik Anis
    </div>
    <!-- Default to the left -->
    <strong>Copyright © 2016 <a href="#">Company</a>.</strong> All rights reserved.
</footer>

resources/views/frontend.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Yunushop Online">
    <meta name="author" content="Yunus">
    <meta name="keywords" content="online shop">

    <title>
        {{ isset($page_title) ? $page_title : 'Butik Anis' }}
    </title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

    <!-- styles -->
    <link href="{{ asset('frontend/css/font-awesome.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/animate.min.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/owl.carousel.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/owl.theme.css') }}" rel="stylesheet">

    <!-- theme stylesheet -->
    <link href="{{ asset('frontend/css/style.default.css') }}" rel="stylesheet" id="theme-stylesheet">

    <!-- your stylesheet with modifications -->
    <link href="{{ asset('frontend/css/custom.css') }}" rel="stylesheet">

    <script src="{{ asset('frontend/js/respond.min.js') }}"></script>
    <script src="https://use.fontawesome.com/3f23df9e0b.js"></script>

    <link rel="shortcut icon" href="{{ asset('frontend/favicon.png') }}">



</head>

<body>

    <!-- *** TOPBAR ***
 _________________________________________________________ -->
    <div id="top">
        <div class="container">
            <div class="col-md-6 offer" data-animate="fadeInDown">
                <a href="{{ url('wellcome') }}" class="btn btn-success btn-sm" data-animate-hover="shake">Selamat Datang!</a>  <a href="{{ url('gallery-produk') }}">Dapatkan produk berkualitas di toko kami.</a>
            </div>
            <div class="col-md-6" data-animate="fadeInDown">
                <ul class="menu">
                  @if(Auth::check())
                    <li><a href="{{ url('/logout') }}" >Logout</a></li>
                    <li><a href="{{ url('/user/cart/account') }}">Area Pelanggan</a></li>
                  @else
                    <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
                  @endif
                    <li><a href="{{ url('about') }}">Profil</a></li>
                    <li><a href="{{ url('cara-belanja') }}">Cara Belanja</a></li>
                    <li><a href="{{ route('konfirmasi.create') }}">Konfirmasi Pembayaran</a></li>
                    <li><a href="{{ url('kontak') }}">Kontak</a></li>
                </ul>
            </div>
        </div>
        <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
            <div class="modal-dialog modal-sm">

                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="Login">Pelanggan Login</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ url('/login') }}" method="post">
                          {{ csrf_field() }}
                          <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                              <label for="email">E-mail</label>

                              <div>
                                  <input id="email-modal"  type="email" class="form-control" name="email" value="{{ old('email') }}">

                                  @if ($errors->has('email'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('email') }}</strong>
                                      </span>
                                  @endif
                              </div>
                          </div>
                          <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                              <label for="password">Password</label>

                              <div>
                                  <input id="password-modal" type="password" class="form-control" name="password">

                                  @if ($errors->has('password'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('password') }}</strong>
                                      </span>
                                  @endif
                              </div>
                          </div>
                            <p class="text-center">
                                <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Login</button>
                            </p>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- *** TOP BAR END *** -->

    <!-- *** NAVBAR ***
 _________________________________________________________ -->

    <div class="navbar navbar-default yamm" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-header">

                <a class="navbar-brand home" href="{{ url('/') }}" data-animate-hover="bounce">
                    <img src="{{ asset('frontend') }}/img/logo.png" alt="YunusSHOP" class="hidden-xs img img-responsive" style="width:80px">
                    <img src="{{ asset('frontend') }}/img/logo.png" alt="YunusSHOP" class="img img-responsive visible-xs img img-responsive" style="width:85px;"><span class="sr-only">Butik Anis</span>
                </a>

                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                      <span style="font-weight: bold;">MENU</span>
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-align-justify"></i>
                    </button>
                </div>

            </div>
            <!--/.navbar-header -->

            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-left">
                    <li class="{{ Request::is('/') ? 'active' : '' }}"><a href="{{ url('/') }}">Home</a></li>
                    <li class="{{ Request::is('about') ? 'active' : '' }}"><a href="{{ url('/about') }}">Profil</a></li>
                    <li class="{{ Request::is('gallery-produk') ? 'active' : '' }}"><a href="{{ url('/gallery-produk') }}">Produk</a></li>
                    <li class="{{ Request::is('blog') ? 'active' : '' }}"><a href="{{ url('/blog') }}">Artikel</a></li>
                    <li class="{{ Request::is('cara-belanja') ? 'active' : '' }}"><a href="{{ url('/cara-belanja') }}">Cara Belanja</a></li>
                    <li class="{{ Request::is('retur') ? 'active' : '' }}"><a href="{{ url('/retur') }}">Retur</a></li>
                    <li class="{{ Request::is('kontak') ? 'active' : '' }}"><a href="{{ url('/kontak') }}">Kontak</a></li>
                    @if (Auth::check())
                      <li class="{{ Request::is('user/cart/account') ? 'active' : '' }}"><a href="{{ url('user/cart/account') }}">Area Pelanggan</a></li>
                    @endif
                </ul>

            </div>
            <!--/.nav-collapse -->

            <div class="navbar-buttons">

                <div class="navbar-collapse collapse right" id="basket-overview">
                    <a href="{{ url('/cart-content') }}" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span class="hidden-sm">{{ Cart::count() }} barang</span></a>
                </div>
                <!--/.nav-collapse -->

                <!--
                <div class="navbar-collapse collapse right" id="search-not-mobile">
                    <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                        <span class="sr-only">Toggle search</span>
                        <i class="fa fa-search"></i>
                    </button>
                </div>
              -->
            </div>

            <div class="collapse clearfix" id="search">

                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">

			<button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

		    </span>
                    </div>
                </form>

            </div>
            <!--/.nav-collapse -->

        </div>
        <!-- /.container -->
    </div>
    <!-- /#navbar -->

    <!-- *** NAVBAR END *** -->
    @yield('content')

        <!-- *** FOOTER ***
 _________________________________________________________ -->
        <div id="footer" data-animate="fadeInUp">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <h4>Halaman Informasi</h4>

                        <ul>
                            <li><a href="{{ url('/about') }}">Profil</a></li>
                            <li><a href="{{ url('/cara-belanja') }}">Cara Belanja</a></li>
                            <li><a href="{{ url('kontak') }}">Kontak</a></li>
                        </ul>

                        <hr>

                        <h4>Area Pelanggan</h4>

                        <ul>
                            <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                            </li>

                        </ul>

                        <hr class="hidden-md hidden-lg hidden-sm">

                    </div>
                    <!-- /.col-md-3 -->

                    <div class="col-md-3 col-sm-6">

                        <h4>Kategori Produk</h4>

                        <ul>
                            @foreach ($kategoriproduk as $d)
                                <li><a href="{{ url('kategori-produk/'.$d->id.'/'.$d->seo) }}">{{ $d->judul }}</a></li>
                            @endforeach
                        </ul>
                        <hr class="hidden-md hidden-lg">

                    </div>
                    <!-- /.col-md-3 -->

                    <div class="col-md-3 col-sm-6">
                        <h4>Kategori Artikel</h4>
                        <ul>
                            @foreach ($kategoriartikel as $d)
                                <li><a href="{{ url('blog/kategori/'.$d->id) }}">{{ $d->judul }}</a></li>
                            @endforeach
                        </ul>


                    </div>
                    <!-- /.col-md-3 -->
                    <div class="col-md-3 col-sm-6">
                        <h4>Kontak Kami</h4>
                        <i class="fa fa-map-marker"></i> Garen RT 02/ IV, Pandeyan, Ngemplak, Boyolali 57375, Jawa Tengah
                        <br><i class="fa fa-phone-square"></i> (0271)720611
                        <br><i class="fa fa-tablet"></i> 08562689459
                        <br><i class="fa fa-whatsapp"></i> 081548213835
                        <br><i class="fa fa-envelope"></i> butik.anis@gmail.com
                    <!-- /.col-md-3 -->

                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#footer -->

        <!-- *** FOOTER END *** -->


        <!-- *** COPYRIGHT ***
 _________________________________________________________ -->
        <div id="copyright">
            <div class="container">
                <div class="col-md-6">
                    <p class="pull-left">© 2016 Butik Anis</p>

                </div>
                <div class="col-md-6">
                    <p class="pull-right">Template by <a href="http://bootstrapious.com/e-commerce-templates">Bootstrapious</a> with support from <a href="https://kakusei.cz">Kakusei</a>
                        <!-- Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
                    </p>
                </div>
            </div>
        </div>
        <!-- *** COPYRIGHT END *** -->



    </div>
    <!-- /#all -->
    <!-- *** SCRIPTS TO INCLUDE ***
 _________________________________________________________ -->
    <script src="{{ asset('frontend/js/jquery-1.11.0.min.js') }}"></script>
    <script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('frontend/js/jquery.cookie.js') }}"></script>
    <script src="{{ asset('frontend/js/waypoints.min.js') }}"></script>
    <script src="{{ asset('frontend/js/modernizr.js') }}"></script>
    <script src="{{ asset('frontend/js/bootstrap-hover-dropdown.js') }}"></script>
    <script src="{{ asset('frontend/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('frontend/js/front.js') }}"></script>


</body>

</html>

resources/views/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo"><b>Butik</b>Anis</a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="user-image" alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" />
                            <p>
                                {{ Auth::user()->name }}- Web Developer
                                <small>Aktif Sejak {{ Auth::user()->created_at }}</small>
                            </p>
                        </li>
                        <!-- Menu Body -->

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profil</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url('/logout') }}" class="btn btn-default btn-flat">Logout</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
<span class="input-group-btn">
  <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
</span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header"><b>MENU</b></li>
            <!-- Optionally, you can add icons to the links -->
            <li><a href="{{ url('admin/pesanan') }}"><span>Pesanan</span></a></li>
            <li><a href="{{ url('admin/laporan') }}"><span>Laporan</span></a></li>
            <li class="treeview">
                <a href="#"><span>Produk</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ url('/admin/produk') }}"><span>Produk</span></a></li>
                    <li><a href="{{ url('/admin/kategori') }}"><span>Kategori</span></a></li>
                </ul>
            </li>
            <li><a href="{{ url('konfirmasi') }}"><span>Konfirmasi Transfer</span></a></li>
            <li><a href="{{ url('confirm') }}"><span>Retur</span></a></li>
            <li><a href="{{ url('/admin/slideshow') }}"><span>Slideshow</span></a></li>
            <li><a href="{{ url('/admin/statis') }}"><span>Halaman Statis</span></a></li>
            <li><a href="{{ url('/admin/ongkir') }}"><span>Ongkir</span></a></li>
            <li class="treeview">
                <a href="#"><span>Artikel</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{{ url('/admin/artikel') }}">Data Artikel</a></li>
                    <li><a href="{{ url('/admin/kategoriartikel') }}">Kategori Artikel</a></li>
                </ul>
            </li>
            <li><a href="{{ url('admin/user') }}"><span>Manajemen User</span></a></li>
            <li><a href="{{ url('/logout') }}"><span>Logout</span></a></li>
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/tinymce.blade.php
<script type="text/javascript" src="{{ URL::asset('tinymce/tinymce.min.js') }}"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link responsivefilemanager charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste image responsivefilemanager"
    ],

    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | responsivefilemanager",
    external_filemanager_path:"/filemanager/",
    filemanager_title:"Responsive Filemanager" ,
    external_plugins: { "filemanager" : "/filemanager/plugin.min.js"}
});
</script>